MOCK_DATA = [
    {
        "sku": "85123A",
        "product_name": "Product A",
        "supplier": "Supplier_A",
        "forecast": 120,
        "horizon_days": 21,
        "stock": 40,
        "incoming": 30,
        "lead_time_days": 14,
        "review_period_days": 7,
        "safety_stock": 20,
        "recommended_order": 70,
        "risk": "HIGH",
        "anomalies_found": 1,
        "explanation": "Ожидаемый спрос превышает доступный запас.",
    },
    {
        "sku": "71053",
        "product_name": "Product B",
        "supplier": "Supplier_B",
        "forecast": 60,
        "horizon_days": 14,
        "stock": 100,
        "incoming": 20,
        "lead_time_days": 7,
        "review_period_days": 7,
        "safety_stock": 12,
        "recommended_order": 0,
        "risk": "LOW",
        "anomalies_found": 0,
        "explanation": "Текущего запаса достаточно для покрытия прогнозируемого спроса.",
    },
    {
        "sku": "84406B",
        "product_name": "Product C",
        "supplier": "Supplier_A",
        "forecast": 180,
        "horizon_days": 21,
        "stock": 55,
        "incoming": 20,
        "lead_time_days": 14,
        "review_period_days": 7,
        "safety_stock": 25,
        "recommended_order": 130,
        "risk": "HIGH",
        "anomalies_found": 2,
        "explanation": "Высокий прогнозируемый спрос при ограниченном доступном запасе.",
    },
    {
        "sku": "21733",
        "product_name": "Product D",
        "supplier": "Supplier_C",
        "forecast": 90,
        "horizon_days": 14,
        "stock": 80,
        "incoming": 15,
        "lead_time_days": 7,
        "review_period_days": 7,
        "safety_stock": 15,
        "recommended_order": 10,
        "risk": "MEDIUM",
        "anomalies_found": 0,
        "explanation": "Запас находится близко к уровню ожидаемого спроса.",
    },
    {
        "sku": "22720",
        "product_name": "Product E",
        "supplier": "Supplier_B",
        "forecast": 45,
        "horizon_days": 14,
        "stock": 80,
        "incoming": 10,
        "lead_time_days": 7,
        "review_period_days": 7,
        "safety_stock": 10,
        "recommended_order": 0,
        "risk": "LOW",
        "anomalies_found": 0,
        "explanation": "Текущего запаса и поставок в пути достаточно.",
    },
    {
        "sku": "85099B",
        "product_name": "Product F",
        "supplier": "Supplier_C",
        "forecast": 150,
        "horizon_days": 21,
        "stock": 35,
        "incoming": 25,
        "lead_time_days": 14,
        "review_period_days": 7,
        "safety_stock": 20,
        "recommended_order": 110,
        "risk": "HIGH",
        "anomalies_found": 1,
        "explanation": "Ожидаемый спрос значительно превышает доступный запас.",
    },
    {
        "sku": "84970L",
        "product_name": "Product G",
        "supplier": "Supplier_A",
        "forecast": 75,
        "horizon_days": 14,
        "stock": 90,
        "incoming": 10,
        "lead_time_days": 7,
        "review_period_days": 7,
        "safety_stock": 12,
        "recommended_order": 0,
        "risk": "LOW",
        "anomalies_found": 0,
        "explanation": "Текущего запаса достаточно на прогнозируемый период.",
    },
    {
        "sku": "84997D",
        "product_name": "Product H",
        "supplier": "Supplier_B",
        "forecast": 110,
        "horizon_days": 21,
        "stock": 50,
        "incoming": 15,
        "lead_time_days": 14,
        "review_period_days": 7,
        "safety_stock": 18,
        "recommended_order": 63,
        "risk": "HIGH",
        "anomalies_found": 0,
        "explanation": "Рекомендуется дополнительный запас для покрытия ожидаемого спроса.",
    },
    {
        "sku": "47566",
        "product_name": "Product I",
        "supplier": "Supplier_C",
        "forecast": 130,
        "horizon_days": 21,
        "stock": 25,
        "incoming": 10,
        "lead_time_days": 14,
        "review_period_days": 7,
        "safety_stock": 20,
        "recommended_order": 115,
        "risk": "HIGH",
        "anomalies_found": 1,
        "explanation": "Текущий запас значительно ниже ожидаемого спроса.",
    },
    {
        "sku": "84945",
        "product_name": "Product J",
        "supplier": "Supplier_A",
        "forecast": 55,
        "horizon_days": 14,
        "stock": 65,
        "incoming": 15,
        "lead_time_days": 7,
        "review_period_days": 7,
        "safety_stock": 10,
        "recommended_order": 0,
        "risk": "LOW",
        "anomalies_found": 0,
        "explanation": "Доступного запаса достаточно.",
    },
]
